// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.1
// source: capwap.proto

package capwap

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FileTransportClient is the client API for FileTransport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileTransportClient interface {
	GetFile(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	PutFile(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
}

type fileTransportClient struct {
	cc grpc.ClientConnInterface
}

func NewFileTransportClient(cc grpc.ClientConnInterface) FileTransportClient {
	return &fileTransportClient{cc}
}

func (c *fileTransportClient) GetFile(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/gbcom.capwap.FileTransport/GetFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileTransportClient) PutFile(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/gbcom.capwap.FileTransport/PutFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileTransportServer is the server API for FileTransport service.
// All implementations must embed UnimplementedFileTransportServer
// for forward compatibility
type FileTransportServer interface {
	GetFile(context.Context, *Message) (*Message, error)
	PutFile(context.Context, *Message) (*Message, error)
	mustEmbedUnimplementedFileTransportServer()
}

// UnimplementedFileTransportServer must be embedded to have forward compatible implementations.
type UnimplementedFileTransportServer struct {
}

func (UnimplementedFileTransportServer) GetFile(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFile not implemented")
}
func (UnimplementedFileTransportServer) PutFile(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutFile not implemented")
}
func (UnimplementedFileTransportServer) mustEmbedUnimplementedFileTransportServer() {}

// UnsafeFileTransportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileTransportServer will
// result in compilation errors.
type UnsafeFileTransportServer interface {
	mustEmbedUnimplementedFileTransportServer()
}

func RegisterFileTransportServer(s grpc.ServiceRegistrar, srv FileTransportServer) {
	s.RegisterService(&FileTransport_ServiceDesc, srv)
}

func _FileTransport_GetFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileTransportServer).GetFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gbcom.capwap.FileTransport/GetFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileTransportServer).GetFile(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileTransport_PutFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileTransportServer).PutFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gbcom.capwap.FileTransport/PutFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileTransportServer).PutFile(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// FileTransport_ServiceDesc is the grpc.ServiceDesc for FileTransport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileTransport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gbcom.capwap.FileTransport",
	HandlerType: (*FileTransportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFile",
			Handler:    _FileTransport_GetFile_Handler,
		},
		{
			MethodName: "PutFile",
			Handler:    _FileTransport_PutFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "capwap.proto",
}
